source("perceptron.R")
data<-read.csv("data.csv", header=F, sep=";")
teste<-read.csv("teste.csv", header=F, sep=";")
model=perceptron(data[,c(1,2,3)], data[,4], iter=100)
test(model, teste[1,c(1,2,3)], 0.5)
train.data<-read.csv("SPECT.train", sep=",", header=F)
test.data<-read.csv("SPECT.test", sep=",", header=F)
model=perceptron(train.data[,1:22], train.data[,23], iter=90)
test(model, test.data[3,1:22], 0.5)